# Generated by Django 4.0.3 on 2022-03-05 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_links_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(max_length=300, validators=[django.core.validators.MaxLengthValidator(5)], verbose_name='Ссылка'),
        ),
    ]
